##Alert Notification CloudHub Connector Properties##
ch:
 password: "![Urr7oSdHxXvg4yt45FXW/w==]"
 
http:
  requester:
    password: "![unqBJjpgQvXkd16Z8VQowPMmsVsmJIBVxcpG6rFAPqhJz9HYoo48VRJN0qYPB7kZ]"  
  preferences:
    client_id:  "![eOGsH5ARGSndi7rncEvXCh/CoQiIbv3mJtWc4luGgn84YOwFEIuIXUcfwwxmarFP]"
    client_secret:  "![ftlgOYbA1porLJIsAgOX+Lf4iQDKg8HbSpEdbM+MX1RFGxxQYK9DVNOYxK3CElJr]"
    tls:
      cert:       
        password: "![c5F+utSCNo1mnB2Jv6JMCw==]" 
  contacts::
    client_id:  "![zwCH1X9OIhufgMqqKj2lXYy3c+eCIB5VHABxpwQkaNzv9m8eux0mq5uWORuQVtWo]"
    client_secret:  "![c/KdInCJYbhCy7/XAQIK2wQkA8rVePfciB/+60zUo/ZlTvfgnq2mXqcvjiO1JqQh]" 
    
##cris customer      
https:
   request: 
     x-clinetid: "![KsKFhsUpR8BtHSyTAwm8RdCDNKZkPUA8H2qsqc8sZTaaHSVNWcJ0RXeLxArUNWwb]"
     x-clientsecret: "![hePCC1veyJCPYIdi1vT1WI/SRAaj2hgVpNIKYgm/lqhz5/JCqA9R7p+cVzBqHuTD]"

tls.keystore:
  password: "![ubKXvsn7pEUKfI6M2g15Yw==]"
  keyPassword: "![ubKXvsn7pEUKfI6M2g15Yw==]"